### ISSUE TITLE
Not switching back to light mode

### ISSUE THREAD

**Issue by axelra82** [katernet/darkmode#12]
I posted the issue here
https://github.com/katernet/darkmode/issues/9#issuecomment-427537778

but it was closed for some reason and I don't know how to re-open it (I have 3 jobs, so sometimes it can take a couple of days before I have the time to answer 😄).

Like it says in the original post... it is switching to dark mode just fine at night. It's just not switching back to light mode in the morning.

I have night shift on my ~4 years old macbook pro with Mojave.

**Comment by katernet** [comment]
Hi. I closed the issue as there was no response, particularly because I asked questions and the answers/results were not provided. I did see you replied again, however the results weren't supplied again.

The log you provided in your original issue is already being discussed in #10 and there is more activity and results in that issue, I would prefer to use that issue for tracking to be honest.

I will leave this issue open a while longer for you due to your commitments, however please note it's quite hard to resolve this type of issue without any testing provided on your behalf.

Please provide the output of below:

```bash
$ launchctl list | grep katernet
$ /usr/libexec/PlistBuddy -c "Print :StartCalendarInterval:Hour" ~/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist
$ sqlite3 ~/Library/Application\ Support/darkmode/solar.db 'SELECT time FROM solar WHERE id=1;' "" 
```

And any errors logged since your last issue.

I would also recommend downloading the latest version [1.8.1](https://github.com/katernet/darkmode/releases/tag/1.8.1) using that version to uninstall (see the README) and running the script again from new. I'm currently investigating the issue in #10

**Comment by katernet** [comment]
Closing as per #10
